version: '2'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.5.60
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - onlyoffice
    # stdin_open: true
    # tty: true
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    command: --max_allowed_packet=32505856
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-document-server
     - onlyoffice-mail-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=root
     - MYSQL_SERVER_PASS=my-secret-pw
     - MAIL_SERVER_API_PORT=8081
     - MAIL_SERVER_API_HOST=onlyoffice-mail-server
     - MAIL_SERVER_DB_HOST=onlyoffice-mysql-server
     - MAIL_SERVER_DB_PORT=3306
     - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
     - MAIL_SERVER_DB_USER=root
     - MAIL_SERVER_DB_PASS=my-secret-pw
    networks:
     - onlyoffice
    ports:
     - '8080:80'
     - '443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./community/data:/var/www/onlyoffice/Data
     - ./community/log:/var/log/onlyoffice
     - ./document/data:/var/www/onlyoffice/DocumentServerData
     - ./certs:/var/www/onlyoffice/Data/certs
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
       - ./document/data:/var/www/onlyoffice/Data
       - ./document/log:/var/log/onlyoffice
       - ./document/document_fonts:/usr/share/fonts/truetype/custom
       - ./document/forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:latest
    depends_on:
     - onlyoffice-mysql-server
    hostname: liumapp.com
    environment:
       - MYSQL_SERVER=onlyoffice-mysql-server
       - MYSQL_SERVER_PORT=3306
       - MYSQL_ROOT_USER=onlyoffice_mailserver_user
       - MYSQL_ROOT_PASSWD=onlyoffice_mailserver_user_pass
       - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    networks:
      - onlyoffice
    restart: always
    privileged: true
    ports: ['25:25','143:143','587:587']
    stdin_open: true
    tty: true
    expose:
      - '8081'
    volumes:
      - ./mail/data:/var/vmail
      - ./certs:/etc/pki/tls/mailserver
      - ./mail/log:/var/log
networks:
  onlyoffice:
    driver: 'bridge'

  
  
